FROM python:3.10-slim
WORKDIR /workspace/train
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY train/ .
COPY archive/ /workspace/archive/
# Creamos la carpeta donde se guardará el modelo dentro del contenedor
RUN mkdir -p /app/modelos
CMD ["python", "train.py"]